# Generated by Django 6.0.1 on 2026-01-10 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('merchant_type', models.CharField(choices=[('PRIMARY', 'Primary School'), ('SECONDARY', 'Secondary School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('OTHER', 'Other')], max_length=20)),
                ('zainbox_code', models.CharField(max_length=50, unique=True)),
                ('settlement_account_number', models.CharField(max_length=20)),
                ('settlement_bank_code', models.CharField(max_length=10)),
                ('approved_by_bank', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(help_text='Dynamic data collected per product')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('channel', models.CharField(blank=True, help_text='card, transfer, ussd', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_reference', models.CharField(max_length=100)),
                ('response_payload', models.JSONField()),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('VARIABLE', 'Variable Amount')], default='FIXED', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required if amount_type is FIXED', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='payments.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.product'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_commission', models.DecimalField(decimal_places=2, max_digits=14)),
                ('merchant_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.SlugField(help_text='Used as metadata key e.g matric_number')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('SELECT', 'Select'), ('DATE', 'Date')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text='Only for SELECT fields', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='payments.product')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('product', 'key')},
            },
        ),
    ]
