# Generated by Django 6.0.1 on 2026-01-12 06:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference when payment method or amount mismatch occurs', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank / platform charge', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('TRANSFER', 'Transfer')], help_text='User-selected payment method', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount paid by customer (amount + fee)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base amount (product amount)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, help_text='Actual payment channel used (card, bank_transfer, ussd)', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('SUCCESS_WITH_ADJUSTMENT', 'Success With Adjustment'), ('FLAGGED', 'Flagged'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
    ]
