# Generated by Django 5.0.6 on 2024-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='button_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
