# Generated by Django 5.0.6 on 2024-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_carousel_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('icon', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
