# Generated by Django 5.0.6 on 2024-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
