"""
Django settings for DjangoApp project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oqj3_7s(opo@b3&7vrlto(f431lf=3314gfh+ldzw+jvi90+or'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.data_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
testing = "My Test"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



ZAINPAY_SECRET_KEY = os.getenv("ZAINPAY_SECRET_KEY")
ZAINPAY_PUBLIC_KEY = os.getenv("ZAINPAY_PUBLIC_KEY")
ZAINPAY_BASE_URL =  os.getenv("ZAINPAY_BASE_URL") # or live URL
# ZAINPAY_SECRET_KEY = "sAszdJctnoAAFHfQKjv28axsX8KWkVqaXHzxGBo4tO0Ca"
# ZAINPAY_PUBLIC_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3phaW5wYXkubmciLCJpYXQiOjE3NjIwODMxMzQsImlkIjo2NDllYjQxZS1kYmZhLTRkM2UtODkzNi1lYTBiODg2NWY5YjgsIm5hbWUiOmF1c21hbjIxQGdtYWlsLmNvbSwicm9sZSI6YXVzbWFuMjFAZ21haWwuY29tLCJzZWNyZXRLZXkiOnNBc3pkSmN0bm9BQUZIZlFLanYyOGF4c1g4S1drVnFhWEh6eEdCbzR0TzBDYX0._Y6AvcbIpazInNFILAZiP5YSGADXtOg6CcQLfZCcYmk"

BASE_URL = os.getenv("BASE_URL")
# BASE_URL = "https://unreformed-hysteroid-telma.ngrok-free.dev"
ZAINPAY_CALLBACK_URL = os.getenv("ZAINPAY_CALLBACK_URL")






# ZAINPAY_BASE_URL = "https://sandbox.zainpay.ng"  # or live URL
# ZAINPAY_SECRET_KEY = "36j7N7tfRV8owtDxxP0ogloF5142bvwjhGbfWWYtcq2lA"
# ZAINPAY_PUBLIC_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3phaW5wYXkubmciLCJpYXQiOjE3NjIwNjg4NzIsImlkIjphMzVlZGRjMC1kNTUxLTRjYjUtOGU0Ni1iZjM0YzRkMTZjZDEsIm5hbWUiOmF1c21hbjIxQGdtYWlsLmNvbSwicm9sZSI6YXVzbWFuMjFAZ21haWwuY29tLCJzZWNyZXRLZXkiOjM2ajdON3RmUlY4b3d0RHh4UDBvZ2xvRjUxNDJidndqaEdiZldXWXRjcTJsQX0.2nD75mPOvYHcYNFeV2A9-yllrjdmowtTCoL14Bb_08Q"

# BASE_URL = "https://unreformed-hysteroid-telma.ngrok-free.dev"
# ZAINPAY_CALLBACK_URL = f"{BASE_URL}/payments/callback/"

